export type SubAgentDescriptor = {
  id: string;
  role: string;
  focus: string;
  /** Plain-text SKILL playbook for this sub-agent (role-specific, from Tavily discovery). */
  skillMd?: string;
};

/** Declarative skills so UI + canvas can show what the specialist can do. */
export type SpecialistSkill = {
  id: string;
  label: string;
  description: string;
  kind: "touch" | "generate" | "orchestrate" | "other";
  /** Full instructional document for this skill (like a SKILL.md per-capability). */
  instructions?: string;
};

export type SpecialistAgentProfile = {
  name: string;
  role: string;
  purpose: string;
  systemInstructions: string;
  allowedTools: string[];
  outputFormat: string;
  apiKeyRefs: string[];
  notes: string;
  /** Declared capabilities inferred from the user mission (browser, OpenClaw fleet, etc.). */
  specializations: string[];
  /** When `openclaw`, the worker attempts a delegated orchestration turn via the OpenClaw CLI. */
  orchestrationMode: "local" | "openclaw";
  /** Child agents the Central Agent intends OpenClaw to coordinate (best-effort stub generation). */
  subAgents?: SubAgentDescriptor[];
  /** Human-readable skills (sentuh web, generate, orkestrasi, …). */
  skills: SpecialistSkill[];
  /** README.md body (Markdown) generated by the Central Agent for this specialist. */
  readmeMd: string;
  /** SKILL.md body — agent playbook (skills, tools, constraints). */
  skillMd?: string;
  /** Saved React Flow position for this agent node. */
  canvasPosition?: { x: number; y: number };
  /** UI canvas lane (icon + color) when multiple specialists are shown. */
  canvasLane?: "frontend" | "backend" | "general";
  /** Stable DB id for canvas persistence across refreshes. */
  persistedId?: string;
  /** Mission that created this agent row. */
  missionId?: string;
};

export type MissionPayload = {
  prompt: string;
  /** Extra knowledge pasted by the user (prepended into the effective mission text). */
  contextNotes?: string;
  /** External URLs (Tavily extract / research); merged into the mission for the Central Agent + tools. */
  referenceUrls?: string[];
  /** When true, tool route runs Tavily search even without “research” keywords in the prompt. */
  preferTavilySearch?: boolean;
  /** User review / test feedback merged into the next mission (human-in-the-loop). */
  motherReviewNotes?: string;
};

export type SubAgentRunResult = {
  id: string;
  role: string;
  focus: string;
  /** Raw model/CLI output for this sub-agent turn. */
  output: string;
  source: "openai-compat" | "openclaw" | "skipped";
};

/** Sequential sub-agent runs + merged report for the Central Agent. */
export type FleetOrchestrationSummary = {
  /** Markdown report consumed by the Central Agent / UI. */
  mergedReport: string;
  subAgentRuns: SubAgentRunResult[];
};

export type MissionResult = {
  missionId: string;
  status: "created" | "running" | "completed" | "failed";
  /** Lead specialist (same as `specialists[0]` when `specialists` is set). */
  profile: SpecialistAgentProfile;
  /** Full squad; omitted or length 1 means a single specialist. */
  specialists?: SpecialistAgentProfile[];
  /** Present when `profile.subAgents` were executed in a fleet loop (not only a single plan). */
  fleetSummary?: FleetOrchestrationSummary;
  /** Central Agent reasoning summary (LLM), shown in knowledge UI. */
  motherBrief?: string;
  /** `mother-llm` when squad came from synthesis; `fallback-rules` when gateway/parse failed. */
  squadSource?: "mother-llm" | "fallback-rules";
  /** Central Agent quality review markdown (per-agent pass/rework). */
  motherReview?: string;
  /** Central Agent aggregated SKILL.md (all squad + sub-agent skills merged). */
  centralSkillMd?: string;
  /** Central Agent aggregated README.md. */
  centralReadmeMd?: string;
  events: string[];
};
