export type SubAgentDescriptor = {
  id: string;
  role: string;
  focus: string;
};

/** Declarative skills so UI + canvas can show what the specialist can do. */
export type SpecialistSkill = {
  id: string;
  label: string;
  description: string;
  kind: "touch" | "generate" | "orchestrate" | "other";
};

export type SpecialistAgentProfile = {
  name: string;
  role: string;
  purpose: string;
  systemInstructions: string;
  allowedTools: string[];
  outputFormat: string;
  apiKeyRefs: string[];
  notes: string;
  /** Declared capabilities inferred from the user mission (browser, OpenClaw fleet, etc.). */
  specializations: string[];
  /** When `openclaw`, the worker attempts a delegated orchestration turn via the OpenClaw CLI. */
  orchestrationMode: "local" | "openclaw";
  /** Child agents the mother intends OpenClaw to coordinate (best-effort stub generation). */
  subAgents?: SubAgentDescriptor[];
  /** Human-readable skills (sentuh web, generate, orkestrasi, …). */
  skills: SpecialistSkill[];
  /** README.md body (Markdown) generated by the mother for this specialist. */
  readmeMd: string;
};

export type MissionPayload = {
  prompt: string;
};

export type MissionResult = {
  missionId: string;
  status: "created" | "running" | "completed" | "failed";
  profile: SpecialistAgentProfile;
  events: string[];
};
