import type { MissionPayload, MissionResult, SpecialistAgentProfile } from "../types";
import { buildMissionGraph } from "./mission-graph";
import { runToolRoute } from "./tool-router";
import { runSandboxTask } from "../sandbox/e2b";

function randomId(length = 8): string {
  return Math.random().toString(36).slice(2, 2 + length);
}

function inferRole(prompt: string): string {
  const lower = prompt.toLowerCase();
  if (lower.includes("scrap") || lower.includes("crawl")) return "research-scraper-agent";
  if (lower.includes("code") || lower.includes("bug") || lower.includes("refactor")) return "coding-agent";
  if (lower.includes("recommend") || lower.includes("suggest")) return "recommendation-agent";
  return "general-specialist-agent";
}

export function generateSpecialistProfile(prompt: string): SpecialistAgentProfile {
  const role = inferRole(prompt);
  return {
    name: `agent-${randomId(6)}`,
    role,
    purpose: "Solve one scoped user mission generated by the mother agent",
    systemInstructions:
      "Stay focused on the assigned role. Return concise, actionable output and explicit next actions.",
    allowedTools: ["tavily-search", "internal-mission-log"],
    outputFormat: "markdown",
    apiKeyRefs: ["OPENAI_API_KEY", "ANTHROPIC_API_KEY", "TAVILY_API_KEY"],
    notes: prompt
  };
}

export async function runMission(payload: MissionPayload): Promise<MissionResult> {
  const missionId = randomId(10);
  const profile = generateSpecialistProfile(payload.prompt);
  const graph = buildMissionGraph(profile);
  const toolEvent = await runToolRoute(payload.prompt);
  const sandboxEvent = await runSandboxTask("echo specialist-agent-ready");

  return {
    missionId,
    status: "completed",
    profile,
    events: [
      `Mission graph steps: ${graph.steps.join(" -> ")}`,
      `Tool route: ${toolEvent}`,
      `Sandbox: ${sandboxEvent}`
    ]
  };
}
