import type { MissionPayload, MissionResult, SpecialistAgentProfile } from "../types";
import { buildMissionGraph } from "./mission-graph";
import { orchestrateViaOpenClaw, shouldRunOpenClaw } from "./openclaw-bridge";
import {
  buildSubAgents,
  inferSpecializations,
  pickOrchestrationMode
} from "./specializations";
import { buildSpecialistReadme, buildSpecialistSkills } from "./specialist-artifacts";
import { runToolRoute } from "./tool-router";
import { runSandboxTask } from "../sandbox/e2b";
import { browserTouchFromPrompt } from "../capabilities/browser";
import { persistMissionResult } from "../db/mission-store";

function randomId(length = 8): string {
  return Math.random().toString(36).slice(2, 2 + length);
}

function inferRole(prompt: string): string {
  const lower = prompt.toLowerCase();
  if (lower.includes("scrap") || lower.includes("crawl")) return "research-scraper-agent";
  if (lower.includes("code") || lower.includes("bug") || lower.includes("refactor")) return "coding-agent";
  if (lower.includes("recommend") || lower.includes("suggest")) return "recommendation-agent";
  if (lower.includes("browser") || lower.includes("playwright") || lower.includes("website")) {
    return "browser-operator-agent";
  }
  if (lower.includes("openclaw") || lower.includes("orchestr")) return "openclaw-fleet-agent";
  return "general-specialist-agent";
}

export function generateSpecialistProfile(prompt: string): SpecialistAgentProfile {
  const role = inferRole(prompt);
  const specializations = inferSpecializations(prompt);
  const orchestrationMode = pickOrchestrationMode(prompt);
  const wantsOpenClaw =
    orchestrationMode === "openclaw" || specializations.includes("openclaw-orchestration");
  const subAgents = wantsOpenClaw ? buildSubAgents(prompt, role) : undefined;

  const allowedTools = new Set<string>(["tavily-search", "internal-mission-log"]);
  if (specializations.includes("browser-automation")) {
    allowedTools.add("tavily-extract");
  }
  if (wantsOpenClaw) {
    allowedTools.add("openclaw-orchestrator");
  }

  const allowed = [...allowedTools];
  const skills = buildSpecialistSkills(role, specializations, allowed);

  const profile: SpecialistAgentProfile = {
    name: `agent-${randomId(6)}`,
    role,
    purpose: "Solve one scoped user mission generated by the mother agent",
    systemInstructions: wantsOpenClaw
      ? "You are a fleet lead: break work across sub-agents, prefer OpenClaw for orchestration when enabled, and keep browser actions explicit."
      : "Stay focused on the assigned role. Return concise, actionable output and explicit next actions.",
    allowedTools: allowed,
    outputFormat: "markdown",
    apiKeyRefs: ["OPENAI_API_KEY", "ANTHROPIC_API_KEY", "TAVILY_API_KEY"],
    notes: prompt,
    specializations,
    orchestrationMode,
    subAgents,
    skills,
    readmeMd: ""
  };

  profile.readmeMd = buildSpecialistReadme(profile, prompt);
  return profile;
}

export async function runMission(payload: MissionPayload): Promise<MissionResult> {
  const missionId = randomId(10);
  const profile = generateSpecialistProfile(payload.prompt);
  const graph = buildMissionGraph(profile);
  const events: string[] = [`Mission graph steps: ${graph.steps.join(" -> ")}`];

  if (profile.specializations.includes("browser-automation")) {
    const browserEvent = await browserTouchFromPrompt(payload.prompt);
    events.push(browserEvent);
  }

  if (shouldRunOpenClaw(profile)) {
    const oc = await orchestrateViaOpenClaw({
      missionId,
      motherPrompt: payload.prompt,
      profile
    });
    events.push(oc);
  }

  const toolEvent = await runToolRoute(payload.prompt);
  events.push(`Tool route: ${toolEvent}`);

  const sandboxEvent = await runSandboxTask("echo specialist-agent-ready");
  events.push(`Sandbox: ${sandboxEvent}`);

  const result: MissionResult = {
    missionId,
    status: "completed",
    profile,
    events
  };

  try {
    const persistence = await persistMissionResult({
      prompt: payload.prompt,
      result
    });

    result.events.push(
      persistence.persisted
        ? "Persistence: mission saved to PostgreSQL"
        : `Persistence skipped: ${persistence.reason}`
    );
  } catch (error) {
    const message = error instanceof Error ? error.message : "unknown database error";
    result.events.push(`Persistence failed: ${message}`);
  }

  return result;
}
