import type { SpecialistAgentProfile, SpecialistSkill } from "../types";

export function buildSpecialistSkills(
  role: string,
  specializations: string[],
  allowedTools: string[]
): SpecialistSkill[] {
  const skills: SpecialistSkill[] = [];

  if (specializations.includes("browser-automation") || allowedTools.includes("tavily-extract")) {
    skills.push({
      id: "touch-web",
      label: "Sentuh web",
      description: "Membaca dan merangkum konten URL lewat Tavily Extract.",
      kind: "touch"
    });
  }

  if (allowedTools.includes("tavily-search")) {
    skills.push({
      id: "research-web",
      label: "Riset web",
      description: "Pencarian & kutipan sumber via Tavily Search.",
      kind: "touch"
    });
  }

  skills.push({
    id: "generate-deliverable",
    label: "Generate output",
    description: "Menghasilkan jawaban terstruktur (markdown, rencana, atau ringkasan misi).",
    kind: "generate"
  });

  if (specializations.includes("openclaw-orchestration") || allowedTools.includes("openclaw-orchestrator")) {
    skills.push({
      id: "orchestrate-fleet",
      label: "Orkestrasi agent",
      description: "Mengatur fleet sub-agent melalui OpenClaw CLI.",
      kind: "orchestrate"
    });
  }

  if (role.includes("coding")) {
    skills.push({
      id: "code-plan",
      label: "Rencana kode",
      description: "Menyusun langkah patch / refactor dari deskripsi bug atau fitur.",
      kind: "generate"
    });
  }

  if (role.includes("nextjs") || role.includes("frontend")) {
    skills.push({
      id: "nextjs-app-router",
      label: "Next.js App Router",
      description: "Struktur route, layout, server/client components untuk halaman artikel/CMS.",
      kind: "generate"
    });
    skills.push({
      id: "html-css-wireframe",
      label: "HTML/CSS wireframe",
      description: "Markup & token warna dasar sebelum komponen React final.",
      kind: "generate"
    });
  }

  if (role.includes("backend") || role.includes("api-")) {
    skills.push({
      id: "rest-contract",
      label: "Kontrak REST",
      description: "Endpoint, status code, dan payload JSON yang konsisten.",
      kind: "generate"
    });
    skills.push({
      id: "sql-schema-sketch",
      label: "Skema data",
      description: "Tabel relasional & indeks untuk artikel, penulis, status publikasi.",
      kind: "generate"
    });
  }

  return skills;
}

/** SKILL.md — playbook for the specialist (shown in dashboard SKILL tab). */
export function buildSpecialistSkillMd(profile: SpecialistAgentProfile, missionPrompt: string): string {
  const skillsBlock = profile.skills
    .map(
      (s) =>
        `### ${s.label} (\`${s.id}\`)\n- **Kind:** ${s.kind}\n- ${s.description}`
    )
    .join("\n\n");

  const tools = profile.allowedTools.length
    ? profile.allowedTools.map((t) => `- \`${t}\``).join("\n")
    : "- _none_";

  return [
    `# SKILL — ${profile.name}`,
    "",
    "> Playbook agent ini. Mother + fleet memakai ini sebagai kontrak perilaku.",
    "",
    "## Kapan memakai agent ini",
    profile.purpose,
    "",
    "## Misi user (ringkas)",
    "```text",
    (missionPrompt.trim() || "(empty)").slice(0, 1200),
    "```",
    "",
    "## Skills",
    skillsBlock || "_No skills declared._",
    "",
    "## Tools",
    tools,
    "",
    "## Instruksi sistem",
    profile.systemInstructions || "_Default._",
    "",
    "## Spesialisasi",
    profile.specializations.map((s) => `- \`${s}\``).join("\n") || "- core-mission",
    "",
    "## Output",
    `- Format: **${profile.outputFormat}**`,
    profile.canvasLane ? `- Canvas lane: **${profile.canvasLane}**` : "",
    "",
    "## Larangan umum",
    "- Jangan klaim sudah menjalankan perintah shell/browser kecuali konteks fleet menyatakan demikian.",
    "- Untuk landing/HTML: hasil harus ada di fence ` ```html ` di README bila diminta user.",
    "",
    "---",
    "_Generated by Mother — edit di UI jika perlu._"
  ]
    .filter(Boolean)
    .join("\n");
}

export function buildSpecialistReadme(profile: SpecialistAgentProfile, missionPrompt: string): string {
  const skillsBlock = profile.skills
    .map((s) => `- **${s.label}** (\`${s.id}\`, ${s.kind}): ${s.description}`)
    .join("\n");

  const tools = profile.allowedTools.length ? profile.allowedTools.map((t) => `\`${t}\``).join(", ") : "_none_";

  return [
    `# ${profile.name}`,
    "",
    `> Specialist dibuat oleh **mother agent** Recursive Agent.`,
    "",
    "## Peran",
    `- **Role:** \`${profile.role}\``,
    `- **Purpose:** ${profile.purpose}`,
    "",
    "## Misi awal (user prompt)",
    "```text",
    missionPrompt.trim() || "(empty)",
    "```",
    "",
    "## Skills (jaminan perilaku)",
    skillsBlock,
    "",
    "## Tools yang diizinkan",
    tools,
    "",
    "## Instruksi sistem",
    profile.systemInstructions || "_Default mother instructions._",
    "",
    "## Output",
    `- Format: **${profile.outputFormat}**`,
    "",
    "---",
    "_README ini di-generate otomatis; edit manual di UI jika perlu._",
    "",
    "> Lihat tab **SKILL.md** di dashboard untuk playbook lengkap agent ini."
  ].join("\n");
}

export function attachSpecialistArtifacts(
  profile: SpecialistAgentProfile,
  missionPrompt: string
): void {
  if (!profile.skillMd?.trim()) {
    profile.skillMd = buildSpecialistSkillMd(profile, missionPrompt);
  }
  if (!profile.readmeMd?.trim()) {
    profile.readmeMd = buildSpecialistReadme(profile, missionPrompt);
  }
}
