import type { SpecialistAgentProfile } from "../types";
import { attachSpecialistArtifacts, buildSpecialistSkills } from "./specialist-artifacts";
import { buildSubAgents, inferSpecializations, pickOrchestrationMode } from "./specializations";

function randomId(length = 8): string {
  return Math.random().toString(36).slice(2, 2 + length);
}

function inferRole(prompt: string): string {
  const lower = prompt.toLowerCase();
  if (lower.includes("scrap") || lower.includes("crawl")) return "research-scraper-agent";
  if (lower.includes("code") || lower.includes("bug") || lower.includes("refactor")) return "coding-agent";
  if (lower.includes("recommend") || lower.includes("suggest")) return "recommendation-agent";
  if (lower.includes("browser") || lower.includes("playwright") || lower.includes("website")) {
    return "browser-operator-agent";
  }
  if (lower.includes("openclaw") || lower.includes("orchestr")) return "openclaw-fleet-agent";
  return "general-specialist-agent";
}

function isWebStackPrompt(p: string): boolean {
  return /(web|website|webapp|web\s*app|\bapp\b|\bui\b|\bux\b|landing|saas|cms|blog|article|e-?commerce|marketplace|dashboard|portal|next\.?js|nextjs|react|vue|svelte|html|css|frontend|back\s*end|full\s*stack|fullstack|\bapi\b|rest|graphql|database|postgres|mysql|prisma|supabase)/i.test(
    p
  );
}

/** Natural language: product-style web work → split frontend + backend specialists. */
function wantsFrontendBackendSquad(p: string): boolean {
  const x = p.toLowerCase();
  if (!isWebStackPrompt(x)) return false;
  if (/(landing|landing\s*page|halaman|homepage|one-?page|crypto|saas|ui|html|css)/i.test(x)) {
    return true;
  }
  if (
    /(cms|content\s*management|artikel|article|blog|editorial|e-?commerce|marketplace|platform|dashboard|admin|portal|full\s*stack|fullstack|lipat|depan\s*dan\s*belakang|frontend\s*(dan|&|\+)\s*backend|backend\s*(dan|&|\+)\s*frontend|ui\s*(dan|&|\+)\s*api|api\s*(dan|&|\+)\s*database|buat\s+web|bikin\s+web|bangun\s+web|situs|aplikasi\s+web)/i.test(
      x
    )
  ) {
    return true;
  }
  if (/(buat|bikin|bangun).{0,60}(web|website|aplikasi|situs|landing|halaman|page|html|ui|crypto)/i.test(x)) {
    return true;
  }
  return false;
}

function baseAllowedTools(specializations: string[], wantsOpenClaw: boolean): string[] {
  const allowedTools = new Set<string>(["tavily-search", "internal-mission-log"]);
  if (specializations.includes("browser-automation")) {
    allowedTools.add("tavily-extract");
  }
  if (wantsOpenClaw) {
    allowedTools.add("openclaw-orchestrator");
  }
  return [...allowedTools];
}

function buildSingletonSpecialist(prompt: string): SpecialistAgentProfile {
  const role = inferRole(prompt);
  const specializations = inferSpecializations(prompt);
  const orchestrationMode = pickOrchestrationMode(prompt);
  const wantsOpenClaw =
    orchestrationMode === "openclaw" || specializations.includes("openclaw-orchestration");
  const subAgents = wantsOpenClaw ? buildSubAgents(prompt, role) : undefined;
  const allowed = baseAllowedTools(specializations, wantsOpenClaw);
  const skills = buildSpecialistSkills(role, specializations, allowed);

  const profile: SpecialistAgentProfile = {
    name: `agent-${randomId(6)}`,
    role,
    purpose: "Solve one scoped user mission generated by the Central Agent",
    systemInstructions: wantsOpenClaw
      ? "You are a fleet lead: break work across sub-agents, prefer OpenClaw for orchestration when enabled, and keep browser actions explicit."
      : "Stay focused on the assigned role. Return concise, actionable output and explicit next actions.",
    allowedTools: allowed,
    outputFormat: "markdown",
    apiKeyRefs: ["OPENAI_API_KEY", "ANTHROPIC_API_KEY", "TAVILY_API_KEY"],
    notes: prompt,
    specializations,
    orchestrationMode,
    subAgents,
    skills,
    readmeMd: "",
    canvasLane: "general"
  };

  attachSpecialistArtifacts(profile, prompt);
  return profile;
}

function buildFrontendSpecialist(prompt: string): SpecialistAgentProfile {
  const role = "nextjs-frontend-agent";
  const specializations = inferSpecializations(prompt);
  const extraSpecs = specializations.includes("web-stack-split")
    ? specializations
    : [...specializations.filter((s) => s !== "core-mission"), "web-stack-split", "web-frontend"];
  const orchestrationMode = pickOrchestrationMode(prompt);
  const wantsOpenClaw =
    orchestrationMode === "openclaw" || specializations.includes("openclaw-orchestration");
  const subAgents = wantsOpenClaw ? buildSubAgents(prompt, role) : undefined;
  const allowed = baseAllowedTools(specializations, wantsOpenClaw);
  const skills = buildSpecialistSkills(role, extraSpecs, allowed);

  const profile: SpecialistAgentProfile = {
    name: `fe-${randomId(5)}`,
    role,
    purpose: "Membangun UI/UX dan deliverable web yang selaras dengan misi user (bukan template generik).",
    systemInstructions:
      "Kamu spesialis frontend: Next.js, aksesibilitas dasar, state form editor, dan pemisahan data fetching ke API backend. Utamakan struktur folder yang mudah di-review.",
    allowedTools: allowed,
    outputFormat: "markdown",
    apiKeyRefs: ["OPENAI_API_KEY", "ANTHROPIC_API_KEY", "TAVILY_API_KEY"],
    notes: prompt,
    specializations: extraSpecs,
    orchestrationMode,
    subAgents,
    skills,
    readmeMd: "",
    canvasLane: "frontend"
  };

  attachSpecialistArtifacts(profile, prompt);
  return profile;
}

function buildBackendSpecialist(prompt: string): SpecialistAgentProfile {
  const role = "api-backend-agent";
  const specializations = inferSpecializations(prompt);
  const extraSpecs = specializations.includes("web-stack-split")
    ? specializations
    : [...specializations.filter((s) => s !== "core-mission"), "web-stack-split", "web-backend"];
  const orchestrationMode: "local" | "openclaw" = "local";
  const allowed = baseAllowedTools(specializations, false);
  const skills = buildSpecialistSkills(role, extraSpecs, allowed);

  const profile: SpecialistAgentProfile = {
    name: `be-${randomId(5)}`,
    role,
    purpose: "Merancang API, model data, dan kontrak integrasi sesuai misi user.",
    systemInstructions:
      "Kamu spesialis backend: REST/JSON konsisten, validasi input, idempotensi di mana relevan, dan skema DB yang mudah dimigrasi (Prisma/SQL).",
    allowedTools: allowed,
    outputFormat: "markdown",
    apiKeyRefs: ["OPENAI_API_KEY", "ANTHROPIC_API_KEY", "TAVILY_API_KEY", "DATABASE_URL"],
    notes: prompt,
    specializations: extraSpecs,
    orchestrationMode,
    skills,
    readmeMd: "",
    canvasLane: "backend"
  };

  attachSpecialistArtifacts(profile, prompt);
  return profile;
}

/**
 * Returns one or more specialist profiles. Web/CMS-style missions infer a **frontend + backend** pair
 * with distinct canvas lanes and README artifacts (HTML/CSS, Next structure, API sketch).
 */
export function inferSpecialistSquad(prompt: string): SpecialistAgentProfile[] {
  if (wantsFrontendBackendSquad(prompt)) {
    return [buildFrontendSpecialist(prompt), buildBackendSpecialist(prompt)];
  }
  return [buildSingletonSpecialist(prompt)];
}
