import type { SpecialistAgentProfile } from "../types";
import { attachSpecialistArtifacts, buildSpecialistSkills } from "./specialist-artifacts";
import { buildSubAgents, inferSpecializations, pickOrchestrationMode } from "./specializations";

function randomId(length = 8): string {
  return Math.random().toString(36).slice(2, 2 + length);
}

function inferRole(prompt: string): string {
  const lower = prompt.toLowerCase();

  const keywords = lower
    .replace(/[^a-z0-9\s-]/g, " ")
    .split(/\s+/)
    .filter((w) => w.length > 3)
    .filter((w) => !["want", "need", "make", "give", "with", "that", "this", "from", "have", "will", "should", "could", "would", "about", "buat", "bikin", "yang", "dengan", "untuk", "dari", "harus", "bisa"].includes(w));

  const topKeywords = keywords.slice(0, 3).join("-");

  if (topKeywords.length > 5) return `${topKeywords}-agent`;
  return "mission-specialist-agent";
}

/**
 * Only true when the user explicitly wants to BUILD a web application.
 * Analysis, validation, audit, strategy prompts should NOT trigger this.
 */
function wantsFrontendBackendSquad(p: string): boolean {
  const x = p.toLowerCase();
  const isBuildIntent = /(buat|bikin|bangun|build|create|develop|implement|code|koding|coding)/i.test(x);
  if (!isBuildIntent) return false;

  const hasWebTarget = /(web|website|webapp|web\s*app|landing\s*page|halaman|homepage|next\.?js|nextjs|react|vue|svelte|html|css|frontend.*backend|full\s*stack|fullstack|buat\s+web|bikin\s+web|bangun\s+web|situs|aplikasi\s+web)/i.test(x);
  return hasWebTarget;
}

function baseAllowedTools(specializations: string[], wantsOpenClaw: boolean): string[] {
  const allowedTools = new Set<string>(["tavily-search", "internal-mission-log"]);
  if (specializations.includes("browser-automation")) {
    allowedTools.add("tavily-extract");
  }
  if (wantsOpenClaw) {
    allowedTools.add("openclaw-orchestrator");
  }
  return [...allowedTools];
}

function buildSingletonSpecialist(prompt: string): SpecialistAgentProfile {
  const role = inferRole(prompt);
  const specializations = inferSpecializations(prompt);
  const orchestrationMode = pickOrchestrationMode(prompt);
  const wantsOpenClaw =
    orchestrationMode === "openclaw" || specializations.includes("openclaw-orchestration");
  const subAgents = wantsOpenClaw ? buildSubAgents(prompt, role) : undefined;
  const allowed = baseAllowedTools(specializations, wantsOpenClaw);
  const skills = buildSpecialistSkills(role, specializations, allowed);

  const profile: SpecialistAgentProfile = {
    name: `agent-${randomId(6)}`,
    role,
    purpose: "Solve one scoped user mission generated by the Central Agent",
    systemInstructions: wantsOpenClaw
      ? "You are a fleet lead: break work across sub-agents, prefer OpenClaw for orchestration when enabled, and keep browser actions explicit."
      : "Stay focused on the assigned role. Return concise, actionable output and explicit next actions.",
    allowedTools: allowed,
    outputFormat: "markdown",
    apiKeyRefs: ["OPENAI_API_KEY", "ANTHROPIC_API_KEY", "TAVILY_API_KEY"],
    notes: prompt,
    specializations,
    orchestrationMode,
    subAgents,
    skills,
    readmeMd: "",
    canvasLane: "general"
  };

  attachSpecialistArtifacts(profile, prompt);
  return profile;
}

function buildFrontendSpecialist(prompt: string): SpecialistAgentProfile {
  const role = "nextjs-frontend-agent";
  const specializations = inferSpecializations(prompt);
  const extraSpecs = specializations.includes("web-stack-split")
    ? specializations
    : [...specializations.filter((s) => s !== "core-mission"), "web-stack-split", "web-frontend"];
  const orchestrationMode = pickOrchestrationMode(prompt);
  const wantsOpenClaw =
    orchestrationMode === "openclaw" || specializations.includes("openclaw-orchestration");
  const subAgents = wantsOpenClaw ? buildSubAgents(prompt, role) : undefined;
  const allowed = baseAllowedTools(specializations, wantsOpenClaw);
  const skills = buildSpecialistSkills(role, extraSpecs, allowed);

  const profile: SpecialistAgentProfile = {
    name: `fe-${randomId(5)}`,
    role,
    purpose: "Membangun UI/UX dan deliverable web yang selaras dengan misi user (bukan template generik).",
    systemInstructions:
      "Kamu spesialis frontend: Next.js, aksesibilitas dasar, state form editor, dan pemisahan data fetching ke API backend. Utamakan struktur folder yang mudah di-review.",
    allowedTools: allowed,
    outputFormat: "markdown",
    apiKeyRefs: ["OPENAI_API_KEY", "ANTHROPIC_API_KEY", "TAVILY_API_KEY"],
    notes: prompt,
    specializations: extraSpecs,
    orchestrationMode,
    subAgents,
    skills,
    readmeMd: "",
    canvasLane: "frontend"
  };

  attachSpecialistArtifacts(profile, prompt);
  return profile;
}

function buildBackendSpecialist(prompt: string): SpecialistAgentProfile {
  const role = "api-backend-agent";
  const specializations = inferSpecializations(prompt);
  const extraSpecs = specializations.includes("web-stack-split")
    ? specializations
    : [...specializations.filter((s) => s !== "core-mission"), "web-stack-split", "web-backend"];
  const orchestrationMode: "local" | "openclaw" = "local";
  const allowed = baseAllowedTools(specializations, false);
  const skills = buildSpecialistSkills(role, extraSpecs, allowed);

  const profile: SpecialistAgentProfile = {
    name: `be-${randomId(5)}`,
    role,
    purpose: "Merancang API, model data, dan kontrak integrasi sesuai misi user.",
    systemInstructions:
      "Kamu spesialis backend: REST/JSON konsisten, validasi input, idempotensi di mana relevan, dan skema DB yang mudah dimigrasi (Prisma/SQL).",
    allowedTools: allowed,
    outputFormat: "markdown",
    apiKeyRefs: ["OPENAI_API_KEY", "ANTHROPIC_API_KEY", "TAVILY_API_KEY", "DATABASE_URL"],
    notes: prompt,
    specializations: extraSpecs,
    orchestrationMode,
    skills,
    readmeMd: "",
    canvasLane: "backend"
  };

  attachSpecialistArtifacts(profile, prompt);
  return profile;
}

/**
 * Returns one or more specialist profiles. Web/CMS-style missions infer a **frontend + backend** pair
 * with distinct canvas lanes and README artifacts (HTML/CSS, Next structure, API sketch).
 */
export function inferSpecialistSquad(prompt: string): SpecialistAgentProfile[] {
  if (wantsFrontendBackendSquad(prompt)) {
    return [buildFrontendSpecialist(prompt), buildBackendSpecialist(prompt)];
  }
  return [buildSingletonSpecialist(prompt)];
}
